All: program

program:
	javac -d . SearchTree.java -Xlint:unchecked
	javac -d . ArrayBST.java -Xlint:unchecked
	javac -d . BinaryTree.java -Xlint:unchecked
	javac -d . BinaryHeap.java -Xlint:unchecked
	javac -d . HW5.java -Xlint:unchecked
	 
	javadoc -d doc SearchTree.java ArrayBST.java BinaryTree.java BinaryHeap.java HW5.java
	
	java hw5.HW5
