All: program

program:
	javac -d . Graph.java
	javac -d . DynamicGraph.java
	javac -d . MyGraph.java
	javac -d . HW8.java
	
	javadoc -d doc Graph.java DynamicGraph.java MyGraph.java HW8.java
	
	java hw8.HW8
