All: program

program:
	javac -d . MergeSort.java
	javac -d . QuickSort.java
	javac -d . NewSort.java
	javac -d . HW6.java
	 
	javadoc -d doc MergeSort.java QuickSort.java NewSort.java HW6.java
	
	java hw6.HW6
