All: program

program:
	javac -d . LDLinkedList.java
	javac -d . Structure.java
	javac -d . Building.java
	javac -d . Playground.java
	javac -d . House.java
	javac -d . Market.java
	javac -d . Office.java
	javac -d . StructureContainer.java
	javac -d . StreetContainer.java
	javac -d . Street.java
	javac -d . Menu.java
	javac -d . HW3_LDLinkedList.java
	
	javadoc -d doc LDLinkedList.java Structure.java Building.java Playground.java House.java Market.java Office.java StructureContainer.java StreetContainer.java Street.java Menu.java HW3_LDLinkedList.java
	
	java hw3_ldlinkedlist.HW3_LDLinkedList
