All: program

program:
	javac -d . SearchTree.java
	javac -d . BinaryTree.java
	javac -d . BinarySearchTree.java
	javac -d . HW7.java
	 
	javadoc -d doc SearchTree.java BinaryTree.java BinarySearchTree.java HW7.java
	
	java hw7.HW7
